### ISSUE TITLE
depth option in CLI gives traceback

### ISSUE THREAD

**Issue by aeromorrison** [dagraham/etm-tk#31]
When the '-d' option is used in the command line interface and its value causes a reduction in the tree, a traceback is thrown. If '-d' is large enough to include the whole report tree, then it does not give an error. It also seems as if the -d option in the CLI is zero-based, while it is one-based in the GUI.

With the following options, the traceback below results:
a w; k[0]; k[1] -b -1/1 -e 1 -f lcb -d 2

Traceback (most recent call last):
  File "C:\Python33\Scripts\etm.py", line 39, in <module>
    data.main(etmdir, sys.argv)
  File "C:\Python33\lib\site-packages\etmTk\data.py", line 6987, in main
    res = c.do_command(argstr)
  File "C:\Python33\lib\site-packages\etmTk\data.py", line 6208, in do_command
    res = self.cmdDict[cmd](arg_str)
  File "C:\Python33\lib\site-packages\etmTk\data.py", line 6779, in do_c
    self.options)
  File "C:\Python33\lib\site-packages\etmTk\data.py", line 4080, in getReportData
    res = tallyByGroup(items, max_level=depth, options=options)
  File "C:\Python33\lib\site-packages\etmTk\data.py", line 2457, in tallyByGroup
    summary, uid, trailing = auglst[i][-1].split('!!')
ValueError: need more than 1 value to unpack

If changed to '-d 3', then it gives the whole report (identical to not having any -d option), which is actually 4 levels deep. Everything works fine in the GUI.

**Comment by dagraham** [comment]
Adam,

I hope this is fixed in 3.1.33. Sorry for taking so long.

-Dan
