### ISSUE TITLE
Program doesn't start if ~/.etm is missing

### ISSUE THREAD

**Issue by orlitzky** [dagraham/etm-tk#62]
It looks like issue #23 is back for me... with v3.2.27:

```
$ etm 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/etm", line 83, in <module>
    view.main(dir=etmdir)
  File "/usr/lib64/python3.4/site-packages/etmTk/view.py", line 4416, in main
    (user_options, options, use_locale) = data.get_options(etmdir)
  File "/usr/lib64/python3.4/site-packages/etmTk/data.py", line 1313, in get_options
    fo = codecs.open(colors_cfg, 'w', dfile_encoding)
  File "/usr/lib64/python3.4/codecs.py", line 891, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/home/mjo/.etm/colors.cfg'
```

A "mkdir" fixes it, but I'm trying to package this for Gentoo, and we can't write to the user's home directory as part of the installation.

**Comment by dagraham** [comment]
What if colors.cfg were written only if the ~/.etm directory already exists?

On Aug 2, 2016, at 6:12 PM, Michael Orlitzky <notifications@github.com<mailto:notifications@github.com>> wrote:


It looks like issue #23<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dagraham_etm-2Dtk_issues_23&d=CwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=cjSGCFDvj7Zy-plAeyNJjDIBRBeNSNbZaJLNyuBRtxo&m=gWKbbU4R7ptYqQMFgO6E0gKwdTe5733-0YOor7mLmuI&s=bW1n2snLZgr4LF_p0C29R4I_8af1X1tWvTw-e-tDqeY&e=> is back for me... with v3.2.27:

$ etm
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/etm", line 83, in <module>
    view.main(dir=etmdir)
  File "/usr/lib64/python3.4/site-packages/etmTk/view.py", line 4416, in main
    (user_options, options, use_locale) = data.get_options(etmdir)
  File "/usr/lib64/python3.4/site-packages/etmTk/data.py", line 1313, in get_options
    fo = codecs.open(colors_cfg, 'w', dfile_encoding)
  File "/usr/lib64/python3.4/codecs.py", line 891, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/home/mjo/.etm/colors.cfg'


A "mkdir" fixes it, but I'm trying to package this for Gentoo, and we can't write to the user's home directory as part of the installation.

**Comment by orlitzky** [comment]
As long as colors.cfg is the only file it tries to create in ~/.etm at startup, I think that will do it.

**Comment by SunyataZero** [comment]
Hi, i think i have the same or a similar problem:
```
sunyata@sunyata-Aspire-ES1-131:~$ etm 
Traceback (most recent call last):
  File "/usr/local/bin/etm", line 83, in <module>
    view.main(dir=etmdir)
  File "/usr/local/lib/python3.5/dist-packages/etmTk/view.py", line 4416, in main
    (user_options, options, use_locale) = data.get_options(etmdir)
  File "/usr/local/lib/python3.5/dist-packages/etmTk/data.py", line 1313, in get_options
    fo = codecs.open(colors_cfg, 'w', dfile_encoding)
  File "/usr/lib/python3.5/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/home/sunyata/.etm/colors.cfg'
sunyata@sunyata-Aspire-ES1-131:~$ 
```

This is after installing with `sudo pip3 install -U etmtk` on my Ubuntu 16.04 machine
